[workspace]
members = ["packages/*", "contracts/*"]

[profile.release.package.cw721-base]
codegen-units = 1
incremental = false

[profile.release.package.cw721-metadata-onchain]
codegen-units = 1
incremental = false

[profile.release.package.cw721-fixed-price]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
