[package]
name = "cw721"
version = "0.12.0"
authors = [
    "Ethan Frey <ethanfrey@users.noreply.github.com>",
    "Orkun Külçe <orkun@deuslabs.fi>",
]
edition = "2018"
description = "Definition and types for the CosmWasm-721 NFT interface"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-nfts"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[dependencies]
cw-utils = "0.12.1"
cosmwasm-std = { version = "1.0.0-beta5" }
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta5" }
